using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using Microsoft.VisualBasic;

namespace KinetixModManager;

/// <summary>
/// An accessible, structured editor for the Skyrim/Fallout 4 configuration INI files. Rather than making a
/// screen-reader user edit raw text (and risk a syntax error that stops the game launching), it presents each
/// setting as a navigable "[Section] key = value" row: Enter changes a value, Delete removes a setting, and a
/// button adds one. Every change is written straight back to the file, preserving all comments and untouched keys.
/// </summary>
public partial class Form1
{
    /// <summary>A settings row in the editor list. Carries its parsed entry and reads as "[Section] key = value".</summary>
    private sealed class IniRow
    {
        public IniDocument.Entry Entry { get; }
        public IniRow(IniDocument.Entry entry) => Entry = entry;
        public override string ToString() => Loc.T("ini.row", Entry.Section, Entry.Key, Entry.Value);
    }

    /// <summary>A game INI file offered in the chooser. Reads as the file name, noting when it doesn't exist yet.</summary>
    private sealed class IniFileChoice
    {
        public string Label { get; }
        public string Path { get; }
        public bool Exists { get; }
        public IniFileChoice(string label, string path, bool exists) { Label = label; Path = path; Exists = exists; }
        public override string ToString() => Exists ? Label : Loc.T("ini.chooseMissing", Label);
    }

    /// <summary>
    /// Mods-menu command: lets the user pick one of the active game's configuration INI files and edit it in the
    /// accessible editor. Bethesda-only (Stardew mods use JSON, edited elsewhere).
    /// </summary>
    private void EditGameIni()
    {
        if (!IsBethesdaGame)
        {
            Speak(Loc.T("ini.notApplicable"));
            return;
        }
        List<(string Label, string Path)> files = ModFileSystem.GameIniFiles(_settings.ActiveGame);
        if (files.Count == 0)
        {
            Speak(Loc.T("ini.noFiles"));
            return;
        }
        ChooseIniFileThenEdit(files);
    }

    /// <summary>Shows the accessible file chooser; on Enter it opens the selected INI (creating a missing custom INI).</summary>
    private void ChooseIniFileThenEdit(List<(string Label, string Path)> files)
    {
        var form = new Form
        {
            Text = Loc.T("ini.chooseTitle"),
            Size = new Size(560, 420),
            StartPosition = FormStartPosition.CenterParent,
            KeyPreview = true,
            MinimizeBox = false,
            MaximizeBox = false,
        };
        var layout = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 1, Padding = new Padding(10) };
        var list = new ListBox { Dock = DockStyle.Fill, AccessibleName = Loc.T("ini.chooseListName"), IntegralHeight = false, HorizontalScrollbar = true };
        foreach (var (label, path) in files)
            list.Items.Add(new IniFileChoice(label, path, File.Exists(path)));
        if (list.Items.Count > 0) list.SelectedIndex = 0;
        layout.Controls.Add(list, 0, 0);
        form.Controls.Add(layout);

        list.GotFocus += List_Enter;

        void OpenSelected()
        {
            if (list.SelectedItem is not IniFileChoice choice) return;
            if (!choice.Exists)
            {
                // Only the custom INI is safe to create out of nothing; the main/prefs INIs are generated by the game.
                if (!choice.Path.EndsWith("Custom.ini", StringComparison.OrdinalIgnoreCase))
                {
                    Speak(Loc.T("ini.fileMissing", choice.Label));
                    return;
                }
                try
                {
                    string? dir = System.IO.Path.GetDirectoryName(choice.Path);
                    if (dir != null) Directory.CreateDirectory(dir);
                    if (!File.Exists(choice.Path)) File.WriteAllText(choice.Path, "");
                }
                catch (Exception ex)
                {
                    SpeakError(Loc.T("ini.createFailed", choice.Label), ex);
                    return;
                }
            }
            form.Close();
            ShowIniEditor(choice.Path, choice.Label);
        }

        list.KeyDown += (_, e) =>
        {
            if (e.KeyCode == Keys.Enter) { e.Handled = e.SuppressKeyPress = true; OpenSelected(); }
        };
        form.KeyDown += (_, e) => { if (e.KeyCode == Keys.Escape) form.Close(); };
        form.Shown += (_, _) => { Speak(Loc.T("ini.chooseOpening", files.Count)); list.Focus(); };

        StyleDialog(form);
        form.ShowDialog(this);
    }

    /// <summary>The accessible editor for a single INI file at <paramref name="path"/> (<paramref name="fileLabel"/> is its name).</summary>
    private void ShowIniEditor(string path, string fileLabel)
    {
        IniDocument doc;
        try { doc = IniDocument.Load(path); }
        catch (Exception ex) { SpeakError(Loc.T("ini.loadFailed", fileLabel), ex); return; }

        var form = new Form
        {
            Text = Loc.T("ini.editorTitle", fileLabel),
            Size = new Size(820, 560),
            StartPosition = FormStartPosition.CenterParent,
            KeyPreview = true,
            MinimizeBox = false,
            MaximizeBox = false,
        };
        var layout = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 2, Padding = new Padding(10) };
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));

        var list = new ListBox { Dock = DockStyle.Fill, AccessibleName = Loc.T("ini.listName", fileLabel), IntegralHeight = false, HorizontalScrollbar = true };

        void Reload(int selectIndex)
        {
            list.BeginUpdate();
            list.Items.Clear();
            foreach (IniDocument.Entry e in doc.Entries()) list.Items.Add(new IniRow(e));
            list.EndUpdate();
            if (list.Items.Count > 0)
                list.SelectedIndex = Math.Min(Math.Max(selectIndex, 0), list.Items.Count - 1);
        }
        Reload(0);

        var btnAdd = new Button { Text = Loc.T("ini.addBtn"), AutoSize = true, AccessibleName = Loc.T("ini.addName") };
        var btnClose = new Button { Text = Loc.T("ini.closeBtn"), AutoSize = true, AccessibleName = Loc.T("ini.closeName") };
        var buttons = new FlowLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, FlowDirection = FlowDirection.LeftToRight };
        buttons.Controls.Add(btnAdd);
        buttons.Controls.Add(btnClose);

        layout.Controls.Add(list, 0, 0);
        layout.Controls.Add(buttons, 0, 1);
        form.Controls.Add(layout);

        list.GotFocus += List_Enter;

        bool SaveDoc()
        {
            try { doc.Save(path); return true; }
            catch (Exception ex) { SpeakError(Loc.T("ini.saveFailed"), ex); return false; }
        }

        void EditSelected()
        {
            if (list.SelectedItem is not IniRow row) return;
            string current = row.Entry.Value;
            string result = Interaction.InputBox(Loc.T("ini.editPrompt", row.Entry.Key, row.Entry.Section), Loc.T("ini.editTitle"), current);
            // Interaction.InputBox can't tell Cancel from an emptied box, so an empty result is treated as "leave it"
            // — a value can't be blanked here (rare for game INIs); Delete removes a setting entirely instead.
            if (result.Length == 0 || result == current) return;

            doc.SetValue(row.Entry.Section, row.Entry.Key, result);
            if (!SaveDoc()) return;
            Reload(list.SelectedIndex);
            Speak(Loc.T("ini.setTo", row.Entry.Key, result));
        }

        void DeleteSelected()
        {
            if (list.SelectedItem is not IniRow row) return;
            if (SpeakBox(Loc.T("ini.deleteConfirm", row.Entry.Key, row.Entry.Section), Loc.T("ini.deleteTitle"),
                    MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes)
                return;

            doc.RemoveKey(row.Entry.Section, row.Entry.Key);
            if (!SaveDoc()) return;
            int idx = list.SelectedIndex;
            Reload(idx);
            if (list.Items.Count == 0) Speak(Loc.T("ini.deletedLast", row.Entry.Key));
            else Speak(Loc.T("ini.deleted", row.Entry.Key));
        }

        void AddSetting()
        {
            string defaultSection = (list.SelectedItem as IniRow)?.Entry.Section ?? "";
            string section = Interaction.InputBox(Loc.T("ini.addSectionPrompt"), Loc.T("ini.addTitle"), defaultSection).Trim();
            if (section.Length == 0) return;
            string key = Interaction.InputBox(Loc.T("ini.addKeyPrompt"), Loc.T("ini.addTitle"), "").Trim();
            if (key.Length == 0) return;
            string value = Interaction.InputBox(Loc.T("ini.addValuePrompt", key), Loc.T("ini.addTitle"), "");

            doc.SetValue(section, key, value);
            if (!SaveDoc()) return;
            Reload(list.Items.Count);
            for (int i = 0; i < list.Items.Count; i++)
                if (list.Items[i] is IniRow r &&
                    r.Entry.Section.Equals(section, StringComparison.OrdinalIgnoreCase) &&
                    r.Entry.Key.Equals(key, StringComparison.OrdinalIgnoreCase))
                { list.SelectedIndex = i; break; }
            Speak(Loc.T("ini.added", key, section));
        }

        btnAdd.Click += (_, _) => AddSetting();
        btnClose.Click += (_, _) => form.Close();
        list.KeyDown += (_, e) =>
        {
            if (e.KeyCode == Keys.Enter) { e.Handled = e.SuppressKeyPress = true; EditSelected(); }
            else if (e.KeyCode == Keys.Delete) { e.Handled = e.SuppressKeyPress = true; DeleteSelected(); }
        };
        form.KeyDown += (_, e) => { if (e.KeyCode == Keys.Escape) form.Close(); };

        form.Shown += (_, _) =>
        {
            Speak(Loc.T("ini.opening", fileLabel, list.Items.Count));
            list.Focus();
        };

        StyleDialog(form);
        form.ShowDialog(this);
    }
}
