using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using Microsoft.VisualBasic;

namespace KinetixModManager;

/// <summary>
/// An accessible, structured editor for the Skyrim/Fallout 4 configuration INI files. Rather than making a
/// screen-reader user edit raw text (and risk a syntax error that stops the game launching), it presents each
/// setting as a navigable "[Section] key = value" row: Enter changes a value, Delete removes a setting, and a
/// button adds one. Every change is written straight back to the file, preserving all comments and untouched keys.
/// </summary>
public partial class Form1
{
    /// <summary>A settings row in the editor list. Carries its parsed entry and reads as "[Section] key = value".</summary>
    private sealed class IniRow
    {
        public IniDocument.Entry Entry { get; }
        public IniRow(IniDocument.Entry entry) => Entry = entry;
        public override string ToString() => Loc.T("ini.row", Entry.Section, Entry.Key, Entry.Value);
    }

    /// <summary>A game INI file offered in the chooser. Reads as the file name, noting when it doesn't exist yet.</summary>
    private sealed class IniFileChoice
    {
        public string Label { get; }
        public string Path { get; }
        public bool Exists { get; }
        public IniFileChoice(string label, string path, bool exists) { Label = label; Path = path; Exists = exists; }
        public override string ToString() => Exists ? Label : Loc.T("ini.chooseMissing", Label);
    }

    /// <summary>
    /// Mods-menu command: lets the user pick one of the active game's configuration INI files and edit it in the
    /// accessible editor: the game's own INIs for Skyrim SE / Fallout 4, and each installed plugin's BepInEx
    /// config file for Moonlight Peaks. Not offered for Stardew Valley, whose mods use JSON.
    /// </summary>
    private void EditGameIni()
    {
        // Skyrim/Fallout 4 have the game's own INIs; Moonlight Peaks has one config file per BepInEx plugin,
        // which is the same format and edits identically. Stardew mods use JSON and are edited elsewhere.
        List<(string Label, string Path)> files;
        if (IsBethesdaGame)
        {
            files = ModFileSystem.GameIniFiles(_settings.ActiveGame, _settings.CurrentGamePath);
        }
        else if (IsBepInExGame)
        {
            files = ModFileSystem.BepInExConfigFiles(_settings.CurrentGamePath);
        }
        else
        {
            Speak(Loc.T("ini.notApplicable"));
            return;
        }

        if (files.Count == 0)
        {
            Speak(Loc.T("ini.noFiles"));
            return;
        }
        ChooseIniFileThenEdit(files);
    }

    /// <summary>Shows the accessible file chooser; on Enter it opens the selected INI (creating a missing custom INI).</summary>
    private void ChooseIniFileThenEdit(List<(string Label, string Path)> files)
    {
        // Shown inside the main window rather than as one of its own — see Form1.InlineView.
        ShowInlineView(Loc.T("ini.chooseTitle"), (container, closeView) =>
        {
        var layout = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 1, Padding = new Padding(10) };
        // Silent for the same reason as the editor's list below: the title and hint have just named this view, and
        // the list is the whole of it.
        var list = new ListBox { Dock = DockStyle.Fill, AccessibleName = SilentAccessibleName, IntegralHeight = false, HorizontalScrollbar = true };
        foreach (var (label, path) in files)
            list.Items.Add(new IniFileChoice(label, path, File.Exists(path)));
        if (list.Items.Count > 0) list.SelectedIndex = 0;
        layout.Controls.Add(list, 0, 0);
        container.Controls.Add(layout);

        // GotFocus announces the position on entry; SelectedIndexChanged keeps announcing "X of Y" as the user
        // arrows through — matching every other list in the app.
        list.GotFocus += List_Enter;
        list.SelectedIndexChanged += List_SelectedIndexChanged;

        void OpenSelected()
        {
            if (list.SelectedItem is not IniFileChoice choice) return;
            if (!choice.Exists)
            {
                // Only the custom INI is safe to create out of nothing; the main/prefs INIs are generated by the game.
                if (!choice.Path.EndsWith("Custom.ini", StringComparison.OrdinalIgnoreCase))
                {
                    Speak(Loc.T("ini.fileMissing", choice.Label));
                    return;
                }
                try
                {
                    string? dir = System.IO.Path.GetDirectoryName(choice.Path);
                    if (dir != null) Directory.CreateDirectory(dir);
                    if (!File.Exists(choice.Path)) File.WriteAllText(choice.Path, "");
                }
                catch (Exception ex)
                {
                    SpeakError(Loc.T("ini.createFailed", choice.Label), ex);
                    return;
                }
            }
            // Open the editor as a nested view and leave this chooser open behind it, so Escape from the editor
            // returns here (the file list) and a second Escape closes the chooser back to the main window.
            ShowIniEditor(choice.Path, choice.Label);
        }

        list.KeyDown += (_, e) =>
        {
            // Left/Right would otherwise move the selection like Up/Down in a single-column list box; suppress them.
            if (e.KeyCode == Keys.Left || e.KeyCode == Keys.Right) { e.Handled = e.SuppressKeyPress = true; }
            else if (e.KeyCode == Keys.Enter) { e.Handled = e.SuppressKeyPress = true; OpenSelected(); }
        };
        // Escape is handled by the view itself (see Form1.InlineView).
        return list;
        },
        // As the hint, so it follows the title instead of arriving ahead of it — see the editor below.
        hint: Loc.T("ini.chooseHint", files.Count));
    }

    /// <summary>
    /// Changes one setting whose file told us what it accepts, and returns the new value (or <c>null</c> if the
    /// user backed out).
    ///
    /// A yes/no setting and one with a list of accepted values are both offered as a list to pick from, so
    /// nothing has to be remembered or spelled correctly. A number is typed, but with its permitted range said
    /// up front and checked before saving — BepInEx quietly falls back to the default when it loads a value it
    /// can't use, so an unchecked entry would appear to work and then revert with no explanation.
    /// </summary>
    private string? EditDeclaredSetting(BepInExSetting setting, string current)
    {
        string described = setting.Description.Length > 0 ? setting.Description : "";

        if (setting.HasChoices)
            return ShowChoiceList(
                Loc.T("bepcfg.chooseTitle", setting.Key),
                Loc.T("bepcfg.chooseListName", setting.Key),
                setting.Choices,
                current,
                Loc.T("bepcfg.chooseHint", described, current));

        string prompt = setting.HasRange
            ? Loc.T("bepcfg.promptRange", setting.Key, described, setting.RangeFrom, setting.RangeTo)
            : Loc.T("bepcfg.prompt", setting.Key, described);

        while (true)
        {
            string? typed = ShowTextPrompt(Loc.T("bepcfg.chooseTitle", setting.Key), prompt, current);
            if (typed == null) return null;

            if (BepInExConfigSchema.IsValid(setting, typed, out BepInExConfigSchema.Problem problem))
                return typed;

            // Said, then asked again with what they typed still in the box, so a near-miss is corrected rather
            // than retyped from scratch.
            Speak(ProblemText(setting, problem));
            current = typed;
        }
    }

    /// <summary>Why a typed value was refused, in words.</summary>
    private static string ProblemText(BepInExSetting setting, BepInExConfigSchema.Problem problem) => problem switch
    {
        BepInExConfigSchema.Problem.NotAnAllowedValue => Loc.T("bepcfg.invalidChoice", string.Join(", ", setting.AcceptableValues)),
        BepInExConfigSchema.Problem.NotABoolean       => Loc.T("bepcfg.invalidBoolean"),
        BepInExConfigSchema.Problem.NotANumber        => Loc.T("bepcfg.invalidNumber"),
        BepInExConfigSchema.Problem.OutOfRange        => Loc.T("bepcfg.invalidRange", setting.RangeFrom, setting.RangeTo),
        _                                             => ""
    };

    /// <summary>The accessible editor for a single INI file at <paramref name="path"/> (<paramref name="fileLabel"/> is its name).</summary>
    private void ShowIniEditor(string path, string fileLabel)
    {
        IniDocument doc;
        try { doc = IniDocument.Load(path); }
        catch (Exception ex) { SpeakError(Loc.T("ini.loadFailed", fileLabel), ex); return; }

        // Snapshot the game INIs + load order once before any edits, so a bad change is one restore away.
        CreateSafetyBackup(Loc.T("safety.reasonIni", fileLabel));

        // Shown inside the main window rather than as one of its own — see Form1.InlineView. Opened from the
        // file chooser, this stacks on top of it, so Escape here returns to the file list.
        ShowInlineView(Loc.T("ini.editorTitle", fileLabel), (container, closeView) =>
        {
        var layout = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 2, Padding = new Padding(10) };
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));

        // Deliberately silent, as in the other three settings editors: this list IS the view, and the view has
        // just said "Editing <file>" as its title and "N settings, press Enter…" as its hint. A name here — "<file>
        // settings" — is the same sentence a third time before the user has heard a single setting. See
        // SilentAccessibleName and Form1.StardewConfig.
        var list = new ListBox { Dock = DockStyle.Fill, AccessibleName = SilentAccessibleName, IntegralHeight = false, HorizontalScrollbar = true };

        void Reload(int selectIndex)
        {
            list.BeginUpdate();
            list.Items.Clear();
            foreach (IniDocument.Entry e in doc.Entries()) list.Items.Add(new IniRow(e));
            list.EndUpdate();
            if (list.Items.Count > 0)
                list.SelectedIndex = Math.Min(Math.Max(selectIndex, 0), list.Items.Count - 1);
        }
        Reload(0);

        var btnAdd = new Button { Text = Loc.T("ini.addBtn"), AutoSize = true, AccessibleName = Loc.T("ini.addName") };
        var btnClose = new Button { Text = Loc.T("ini.closeBtn"), AutoSize = true, AccessibleName = Loc.T("ini.closeName") };
        var buttons = new FlowLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, FlowDirection = FlowDirection.LeftToRight };
        buttons.Controls.Add(btnAdd);
        buttons.Controls.Add(btnClose);

        layout.Controls.Add(list, 0, 0);
        layout.Controls.Add(buttons, 0, 1);
        container.Controls.Add(layout);

        // GotFocus announces the position on entry; SelectedIndexChanged keeps announcing "X of Y" as the user
        // arrows through — matching every other list in the app.
        list.GotFocus += List_Enter;
        list.SelectedIndexChanged += List_SelectedIndexChanged;

        bool SaveDoc()
        {
            try { doc.Save(path); return true; }
            catch (Exception ex) { SpeakError(Loc.T("ini.saveFailed"), ex); return false; }
        }

        // What the file says about its own settings. A BepInEx config records each setting's type, its default
        // and exactly what it accepts, directly above the value — so those settings can be offered as choices
        // instead of typed. A Bethesda game INI declares nothing, and this is simply empty for it.
        List<BepInExSetting> schema = BepInExConfigSchema.Read(path);

        void EditSelected()
        {
            if (list.SelectedItem is not IniRow row) return;
            string current = row.Entry.Value;

            BepInExSetting? declared = BepInExConfigSchema.Find(schema, row.Entry.Section, row.Entry.Key);
            string? result = declared != null
                ? EditDeclaredSetting(declared, current)
                : ShowTextPrompt(Loc.T("ini.editTitle"),
                    Loc.T("ini.editPrompt", row.Entry.Key, row.Entry.Section), current);

            // Null is "cancelled". An empty answer is a real one and is kept, which the old pop-up box could not
            // express — it reported a cancelled box and an emptied one identically.
            if (result == null || result == current) return;

            doc.SetValue(row.Entry.Section, row.Entry.Key, result);
            if (!SaveDoc()) return;
            Reload(list.SelectedIndex);
            Speak(Loc.T("ini.setTo", row.Entry.Key, result));
        }

        void DeleteSelected()
        {
            if (list.SelectedItem is not IniRow row) return;
            if (SpeakBox(Loc.T("ini.deleteConfirm", row.Entry.Key, row.Entry.Section), Loc.T("ini.deleteTitle"),
                    MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes)
                return;

            doc.RemoveKey(row.Entry.Section, row.Entry.Key);
            if (!SaveDoc()) return;
            int idx = list.SelectedIndex;
            Reload(idx);
            if (list.Items.Count == 0) Speak(Loc.T("ini.deletedLast", row.Entry.Key));
            else Speak(Loc.T("ini.deleted", row.Entry.Key));
        }

        void AddSetting()
        {
            string defaultSection = (list.SelectedItem as IniRow)?.Entry.Section ?? "";

            string? typedSection = ShowTextPrompt(Loc.T("ini.addTitle"), Loc.T("ini.addSectionPrompt"), defaultSection);
            if (typedSection == null) { Speak(Loc.T("common.changesCancelled")); return; }
            string section = typedSection.Trim();
            if (section.Length == 0) { Speak(Loc.T("ini.addNeedSection")); return; }

            string? typedKey = ShowTextPrompt(Loc.T("ini.addTitle"), Loc.T("ini.addKeyPrompt"), "");
            if (typedKey == null) { Speak(Loc.T("common.changesCancelled")); return; }
            string key = typedKey.Trim();
            if (key.Length == 0) { Speak(Loc.T("ini.addNeedKey")); return; }

            // A value may legitimately be empty — plenty of INI settings are switched off by having nothing after
            // the equals sign — so only Escape backs out here.
            string? value = ShowTextPrompt(Loc.T("ini.addTitle"), Loc.T("ini.addValuePrompt", key), "");
            if (value == null) { Speak(Loc.T("common.changesCancelled")); return; }

            doc.SetValue(section, key, value);
            if (!SaveDoc()) return;
            Reload(list.Items.Count);
            for (int i = 0; i < list.Items.Count; i++)
                if (list.Items[i] is IniRow r &&
                    r.Entry.Section.Equals(section, StringComparison.OrdinalIgnoreCase) &&
                    r.Entry.Key.Equals(key, StringComparison.OrdinalIgnoreCase))
                { list.SelectedIndex = i; break; }
            Speak(Loc.T("ini.added", key, section));
        }

        btnAdd.Click += (_, _) => AddSetting();
        btnClose.Click += (_, _) => closeView();
        list.KeyDown += (_, e) =>
        {
            // Left/Right would otherwise move the selection like Up/Down in a single-column list box; suppress them.
            if (e.KeyCode == Keys.Left || e.KeyCode == Keys.Right) { e.Handled = e.SuppressKeyPress = true; }
            else if (e.KeyCode == Keys.Enter) { e.Handled = e.SuppressKeyPress = true; EditSelected(); }
            else if (e.KeyCode == Keys.Delete) { e.Handled = e.SuppressKeyPress = true; DeleteSelected(); }
        };
        // Escape is handled by the view itself (see Form1.InlineView).

        return list;
        },
        // The opening words go through ShowInlineView's hint, not a Speak in here. Anything spoken while the view
        // is being built lands BEFORE the title, so this used to say the whole sentence, then hear the title say
        // "Editing <file>" over again, then the list name say "<file> settings" a third time. As the hint it
        // follows the title and completes it, which is how the other three settings editors read.
        hint: Loc.T("ini.hint", doc.Entries().Count()));
    }
}
